---
# TODO: Add a bunch of other things here like installing Homebrew, installing packages from .Brewfile etc.
#       ref: https://github.com/TalkingQuickly/ansible-osx-setup/blob/master/ansible_osx.yml

- name: Main dotfiles play
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - role: macos_config
      when: ansible_facts['os_family'] == 'Darwin'
