[project]
name = "dotfiles-ansible"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible>=11.7.0",
]

[dependency-groups]
dev = [
    "ansible-lint>=25.6.1",
    "yamllint>=1.37.1",
]
