"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[directory]
truncation_length = 50
truncation_symbol = ""
truncate_to_repo = true
style = "bold 251"

[package]
disabled = true

[aws]
disabled = true

[battery]
disabled = true

[cmd_duration]
disabled = true

[python]
symbol = " "
format = '[(${symbol}[$virtualenv](bold bright-green) )](bright-green)'

[git_branch]
# the remote branch is shown only if it is different from the local branch
format = "[$symbol$branch(:$remote_name/$remote_branch)]($style) "

[git_metrics]
disabled = false

[git_status]
format = '([$all_status$ahead_behind ]($style))'
stashed = ""
