"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[directory]
truncation_length = 50
truncation_symbol = ""
truncate_to_repo = true
style = "bold white"

[package]
disabled = true

[aws]
disabled = true

[battery]
disabled = true

[cmd_duration]
disabled = true

[python]
symbol = " "
format = '[(${symbol}[$virtualenv](bold #ffd343) )](#ffd343)'

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_metrics]
disabled = false

[git_status]
format = '([$all_status$ahead_behind ]($style))'
stashed = ""
