#!/bin/bash

main_branch=$(git branch | grep "^\s*\*\?\s*\(master\|main\)\s*$")

git log --reverse --no-merges --grep="^Problem:" ${main_branch}.. --format="----------------


**%h**

%B" | grep -v -E "^refs" | sed 's_^\(Problem:\|Solution:\)_**\1**_' | tail -n+4 | head -n-2
