#!/bin/bash

git for-each-ref --format="%(authorname);%(refname)" \
    | grep "^$(git config user.name)" \
    | cut -d ";" -f 2 \
    | grep -v "^refs/stash" \
    | grep -v "^refs/remotes" \
    | grep -v "^refs/tags" \
    | cut -d "/" -f 3
