#!/bin/bash

set -e

branch_name=$(git rev-parse --abbrev-ref HEAD)
jira_issue=$(echo -n "$branch_name" | sed -E -n 's|^.*/(([A-Z]{2,}\-[0-9]+)\-)?.*$|\2|p')

if [[ -z "$jira_issue" ]]; then
    echo "error: no JIRA issue found in branch name" >&2
    exit 1
fi

git push --set-upstream origin $branch_name
gh pr create
jira issue move $jira_issue "Code Review"
