#!/bin/bash

set -eo pipefail

SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
source "$SCRIPTS_DIR/common.sh"

if [[ -z "${JIRA_API_TOKEN}" ]]; then
    export JIRA_API_TOKEN=$(op_get_credential "SoftwareOne: JIRA API Token")
fi

if [[ -z "${JIRA_API_TOKEN}" ]]; then
	error "No JIRA API Token provided"
fi

jira sprint list \
    --current \
    --assignee $(jira me) \
    --status "~Done" \
    --order-by "status" \
    --plain 
 
# jira-my-issues | sed '1d' | fzf | awk -F '\t{1,}' '{                                                                                                                           
#     branch_type = "chore";
#     if ($1 == "Story")
#         branch_type = "feat";
#
#     issue_key = $2;
#     issue_summary = $3;
#
#     normalized_summary = tolower(issue_summary);
#     gsub(/[^[:alnum:]]/, " ", normalized_summary);
#     gsub("^ +", "", normalized_summary);
#     gsub(" +$", "", normalized_summary);
#     gsub(" +", "-", normalized_summary);
#
#     printf("%s/%s-%s", branch_type, issue_key, normalized_summary)
# }'
#
# TODO: Add a preview to fzf with `jira issue view $issue_key`
