#!/bin/bash

SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
source "$SCRIPTS_DIR/common.sh"

# TODO: Change to yadm_sync as follows:
# * Check if in merge conflict and if so, resume from the step about the conflict bellow
# * yadm add
# * yadm status
# * If not empty, optionally show diff, confirm commit (abort stops the script)
# * yadm commit
# * yadm pull
# * If merge conflict, deal with it
# * [post pull actons, e.g. make install for scripts, yadm alt, brew install from leaves etc.]
# * If local changes not pushed yet, yadm push

echo -n "Updating brew packages list... "
brew leaves > ~/.brew_leaves.txt
echo "Done"

# Add yadm any new files from these directories
yadm add ~/scripts
yadm add ~/.config/nvim
yadm add ~/.config/tmuxinator

yadm status

if (confirm "Do you want to see the diff?"); then
    yadm diff HEAD
fi

confirm "Are you sure you want to commit these changes?" "y"

commit_msg="Updated dotfiles $(date +'%Y-%m-%d %H:%M %Z') from $(yadm config local.class)"

yadm commit -am "$commit_msg" && yadm push
